apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: multiserve

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml
  - pvc.yaml
  - serviceaccount.yaml
  - networkpolicy.yaml

commonLabels:
  app: multiserve
  managed-by: kustomize

images:
  - name: multiserve-app
    newTag: latest
