apiVersion: v1
kind: Service
metadata:
  name: multiserve-app
  namespace: multiserve
  labels:
    app: multiserve
    component: app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: multiserve
    component: app
---
apiVersion: v1
kind: Service
metadata:
  name: multiserve-lb
  namespace: multiserve
  labels:
    app: multiserve
    component: lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
    - port: 443
      targetPort: 8000
      protocol: TCP
      name: https
  selector:
    app: multiserve
    component: app
