apiVersion: v1
kind: ServiceAccount
metadata:
  name: multiserve-sa
  namespace: multiserve
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/multiserve-app-role
automountServiceAccountToken: true
